apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-nginx
  labels:
    app: nginx # 이 Deployment 객체의 레이블, app=nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webui # 이 Deployment가 선택하는 Pod들의 레이블, app=webui
  template:
    metadata:
      labels:
        app: webui # 이 Deployment로 생성되는 Pod들의 레이블, app=webui
    spec:
      containers:
      - name: nginx-container
        image: nginx:1.14.2
        ports:
        - containerPort: 80
