apiVersion: v1
kind: Service
metadata:
  name: clusterip-service
spec:
  type: ClusterIP
  clusterIP: 10.100.100.100
  selector:
    app: webui #  이 Service가 트래픽을 전달할 Pod들을 선택하는 기준
  ports:
    - protocol: TCP
      port: 80 # 클라이언트가 이 Service에 접근할 때 사용할 포트
      targetPort: 8080 # Service가 선택한 Pod들에서 실제로 트래픽을 전달할 포트
